
INCLUDES = -I . \
           -I /home/daowen/boost/boost_1_62_0

SOURCES = util.cpp \
          attribute.cpp \
          effect.cpp \
          skill.cpp \
          cluster_arrow.cpp \
          role.cpp \
          character.cpp \
          test.m.cpp

all: 
	g++ $(INCLUDES) -std=c++11 -o test.tsk ${SOURCES}

#util.cpp attribute.cpp effect.cpp test.m.cpp
