/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package attendence;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Student student1 = new Student("1", "Joe", "Doe", 2023);
        // Event event1 = new Event();
        System.out.println(student1.toString());
    }
}
