/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package attendence;

import attendence.core.Student;
import attendence.gui.MainFrame;

public class App {
    public String getGreeting() {
        return "Starting Attendance Tracker...";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Student student1 = new Student("1", "Joe", "Doe", 2023);
        // Event event1 = new Event();
        System.out.println(student1.toString());

        new MainFrame();
    }
}
