/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package skillrotation;

import skillrotation.impl.DummyTarget;
import skillrotation.impl.WorldSpaceTime;
import skillrotation.impl.deathknight.BloodStrike;
import skillrotation.impl.deathknight.DeathKnight;
import skillrotation.impl.deathknight.FrostStrike;
import skillrotation.impl.deathknight.Obliterate;
import skillrotation.impl.simulation.ObliterateFrostStrikeBloodStrikeSpam;
import skillrotation.impl.simulation.ObliterateSpam;
import skillrotation.intf.DeathKnightPlayControl;


// TODO
// 1. make WorldSpaceTime non-Singleton
// 2. add resource cooldown
// 3. add new skills for the full rotation
// 4. add file logging
// 5. add journal collection for analysis
// 6. machine time simulation
public class App {
    public static void main(String[] args) throws InterruptedException {
        // runObliterateSpam();
        runObliterateFrostStrikeBloodStrikeSpam();
    }

    private static void runObliterateSpam() throws InterruptedException {
        WorldSpaceTime worldSpaceTime = WorldSpaceTime.getInstance();

        DeathKnight dk1 = new DeathKnight("DK1", 60);
        DeathKnightPlayControl obSpam = new ObliterateSpam(dk1);
        dk1.setControl(obSpam);

        dk1.setSkill(Obliterate.getInstance(4));

        DummyTarget dummy = new DummyTarget();

        dk1.selectTarget(dummy);

        Thread.sleep(18000);
        worldSpaceTime.stop();
    }

    private static void runObliterateFrostStrikeBloodStrikeSpam() throws InterruptedException {
        WorldSpaceTime worldSpaceTime = WorldSpaceTime.getInstance();

        DeathKnight dk1 = new DeathKnight("DK1", 60);
        DeathKnightPlayControl obSpam = new ObliterateFrostStrikeBloodStrikeSpam(dk1);
        dk1.setControl(obSpam);

        dk1.setSkill(Obliterate.getInstance(4));
        dk1.setSkill(FrostStrike.getInstance(6));
        dk1.setSkill(BloodStrike.getInstance(6));

        DummyTarget dummy = new DummyTarget();

        dk1.selectTarget(dummy);

        Thread.sleep(25000);
        worldSpaceTime.stop();
    }
}
