/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package skillrotation;

import skillrotation.impl.Dummy;
import skillrotation.impl.WorldSpaceTime;
import skillrotation.impl.deathknight.DeathKnight;
import skillrotation.impl.deathknight.Obliterate;
import skillrotation.impl.simulation.ObliterateSpam;
import skillrotation.intf.Character;
import skillrotation.intf.PlayControl;

public class App {
    public static void main(String[] args) throws InterruptedException {
        WorldSpaceTime worldSpaceTime = WorldSpaceTime.getInstance();

        DeathKnight dk1 = new DeathKnight("DK1", 60);
        PlayControl obSpam = new ObliterateSpam(dk1);
        dk1.setControl(obSpam);

        Obliterate obliterate = new Obliterate(4);
        dk1.setSkill(obliterate);

        Dummy dummy = new Dummy();

        dk1.selectTarget(dummy);

        Thread.sleep(10000);
        worldSpaceTime.stop();
    }
}
