/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fantasy;

import fantasy.impl.DummyTarget;
import fantasy.impl.WorldSpaceTime;
import fantasy.impl.data.ImmutableIntegerInterval;
import fantasy.impl.deathknight.*;
import fantasy.impl.item.ImmutableWeapon;
import fantasy.impl.item.Weapon;
import fantasy.impl.simulation.ClassicFrostRotation;
import fantasy.impl.simulation.JustKeepFrostFeverUp;
import fantasy.impl.simulation.ObliterateFrostStrikeBloodStrikeSpam;
import fantasy.impl.simulation.ObliterateSpam;
import fantasy.intf.DeathKnightPlayControl;


// TODO
// 1. make WorldSpaceTime non-Singleton
// 2. add resource cooldown (done)
// 3. add new skills for the full rotation
// 4. add file logging
// 5. add journal collection for analysis
// 6. machine time simulation
public class App {
    public static final Weapon REFORGED_TRUESILVER_CHAMPION = ImmutableWeapon.of(
            ImmutableIntegerInterval.of(449, 674), 3600,
            "Reforged Truesilver Champion", Weapon.Style.TwoHandedWeapon, Weapon.Category.Sword);

    public static void main(String[] args) throws InterruptedException {
        // runObliterateSpam();
        // runObliterateFrostStrikeBloodStrikeSpam();
        runJustKeepFrostFeverUp();
    }

    private static DeathKnight createDeathKnight() {
        DeathKnight dk = new DeathKnight("Irevlys", 60);
        dk.setSkill(Obliterate.LEVEL_4);
        dk.setSkill(FrostStrike.LEVEL_6);
        dk.setSkill(BloodStrike.LEVEL_6);
        dk.setSkill(IcyTouch.LEVEL_5);
        dk.equipWeapon(REFORGED_TRUESILVER_CHAMPION);
        return dk;
    }

    private static void runObliterateSpam() throws InterruptedException {
        DeathKnight dk = createDeathKnight();
        DeathKnightPlayControl obSpam = new ObliterateSpam(dk);

        DummyTarget dummy = new DummyTarget();
        dk.selectTarget(dummy);

        Thread.sleep(18000);
        WorldSpaceTime.getInstance().stop();
    }

    private static void runObliterateFrostStrikeBloodStrikeSpam() throws InterruptedException {
        DeathKnight dk = createDeathKnight();
        DeathKnightPlayControl obSpam = new ObliterateFrostStrikeBloodStrikeSpam(dk);

        DummyTarget dummy = new DummyTarget();
        dk.selectTarget(dummy);

        Thread.sleep(25000);
        WorldSpaceTime.getInstance().stop();
    }

    private static void runJustKeepFrostFeverUp() throws InterruptedException {
        DeathKnight dk = createDeathKnight();
        DeathKnightPlayControl justKeepFrostFeverUp = new JustKeepFrostFeverUp(dk);

        DummyTarget dummyTarget = new DummyTarget();
        dk.selectTarget(dummyTarget);

        Thread.sleep(30000);
        WorldSpaceTime.getInstance().stop();
    }

    private static void runClassicFrostRotation() throws InterruptedException {
        DeathKnight dk = createDeathKnight();
        DeathKnightPlayControl classicFrostRotation = new ClassicFrostRotation(dk);

        DummyTarget dummy = new DummyTarget();
        dk.selectTarget(dummy);

        Thread.sleep(45000);
        WorldSpaceTime.getInstance().stop();
    }
}
