/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fantasy;

import fantasy.impl.DummyTarget;
import fantasy.impl.data.ImmutableIntegerInterval;
import fantasy.impl.deathknight.*;
import fantasy.impl.deathknight.playcontrol.ClassicFrostRotation;
import fantasy.impl.deathknight.playcontrol.IcyTouchSpam;
import fantasy.impl.deathknight.playcontrol.PlagueStrikeSpam;
import fantasy.impl.item.ImmutableWeapon;
import fantasy.impl.item.Weapon;
import fantasy.impl.deathknight.DeathKnightPlayControl;
import fantasy.impl.priest.GreaterHeal;
import fantasy.impl.priest.Priest;
import fantasy.impl.priest.playcontrol.GreaterHealSpam;
import fantasy.impl.spacetime.WorldSpaceTime;
import fantasy.intf.PlayControl;

import java.time.Duration;


public class App {
    public static final Weapon REFORGED_TRUESILVER_CHAMPION = ImmutableWeapon.of(
            ImmutableIntegerInterval.of(449, 674), 3600,
            "Reforged Truesilver Champion", Weapon.Style.TwoHandedWeapon, Weapon.Category.Sword);
    public static final Weapon SWORD_OF_JUSTICE = ImmutableWeapon.of(
            ImmutableIntegerInterval.of(514, 772), 3800,
            "Sword of Justice", Weapon.Style.TwoHandedWeapon, Weapon.Category.Sword);

    public static void main(String[] args) throws InterruptedException {
        testPriest();
    }

    private static void testDeathKnight() throws InterruptedException {
        DeathKnight dk = enhanceWithTalents(createBasicDeathKnight());
//        DeathKnightPlayControl obliterateSpam = new ObliterateSpam(dk);
//        DeathKnightPlayControl strikeSpam = new ObliterateFrostStrikeBloodStrikeSpam(dk);
//        DeathKnightPlayControl justKeepFrostFeverUp = new JustKeepFrostFeverUp(dk);
//        DeathKnightPlayControl icyTouchSpam = new IcyTouchSpam(dk, 2);
//        DeathKnightPlayControl plagueStrikeSpam = new PlagueStrikeSpam(dk);
        DeathKnightPlayControl classicFrostRotation = new ClassicFrostRotation(dk);

        runRotation(dk, Duration.ofSeconds(300), true);
    }

    private static void testPriest() {
        Priest priest = createBasicPriest();
        PlayControl greaterHealSpam = new GreaterHealSpam(priest);

        runRotation(priest, Duration.ofSeconds(30));
    }

    private static DeathKnight createBasicDeathKnight() {
        DeathKnight dk = new DeathKnight("Irevlys", 80);
        dk.setSkill(Obliterate.LEVEL_4);
        dk.setSkill(FrostStrike.LEVEL_6);
        dk.setSkill(BloodStrike.LEVEL_6);
        dk.setSkill(IcyTouch.LEVEL_5);
        dk.setSkill(PlagueStrike.LEVEL_6);
//        dk.equipWeapon(REFORGED_TRUESILVER_CHAMPION);
        dk.equipWeapon(SWORD_OF_JUSTICE);
        return dk;
    }

    private static Priest createBasicPriest() {
        Priest priest = new Priest("Letmepull", 80);
        priest.setSkill(GreaterHeal.LEVEL_9);
        return priest;
    }

    private static DeathKnight enhanceWithTalents(DeathKnight dk) {
        // blood talents
        dk.setSubversion(DeathKnightTalentPool.Subversion.LEVEL_3);
        dk.setTwoHandedWeaponSpecialization(DeathKnightTalentPool.TwoHandedWeaponSpecialization.LEVEL_2);
        // frost talents
        dk.setRunicPowerMastery(DeathKnightTalentPool.RunicPowerMastery.LEVEL_2);
        dk.setBlackIce(DeathKnightTalentPool.BlackIce.LEVEL_5);
        dk.setChillOfTheGrave(DeathKnightTalentPool.ChillOfTheGrave.LEVEL_2);
        dk.setGlacierRot(DeathKnightTalentPool.GlacierRot.LEVEL_3);
        dk.setAnnihilation(DeathKnightTalentPool.Annihilation.LEVEL_3);
        dk.setKillingMachine(DeathKnightTalentPool.KillingMachine.LEVEL_5);
        dk.setRime(DeathKnightTalentPool.Rime.LEVEL_3);
        dk.setBloodOfTheNorth(DeathKnightTalentPool.BloodOfTheNorth.LEVEL_3);
        dk.setGuileOfGorefield(DeathKnightTalentPool.GuileOfGorefiend.LEVEL_3);
        // unholy talents
        dk.setViciousStrikes(DeathKnightTalentPool.ViciousStrikes.LEVEL_2);
        dk.setEpidemic(DeathKnightTalentPool.Epidemic.LEVEL_2);
        return dk;
    }

    private static DeathKnight enhanceWithStats(DeathKnight dk) {
        return dk;
    }

    private static void runRotation(DeathKnight dk, Duration duration, boolean useAutoAttack) throws InterruptedException {
        WorldSpaceTime.getInstance().setUp(duration);

        DummyTarget dummy = new DummyTarget();
        WorldSpaceTime.getInstance().getWorldTiming().select(dk, dummy);
//        dk.selectTarget(dummy);
//        if (useAutoAttack) {
//            dk.turnOnAutoAttack();
//        }

        WorldSpaceTime.getInstance().await();
//        WorldSpaceTime.getInstance().start();

//        Thread.sleep(duration.toMillis());
//        dk.turnOffAutoAttack();
//        WorldSpaceTime.getInstance().end();
    }

    private static void runRotation(Priest priest, Duration duration) {
        WorldSpaceTime.getInstance().setUp(duration);

        WorldSpaceTime.getInstance().getWorldTiming().select(priest, priest);

        WorldSpaceTime.getInstance().await();
    }
}
