/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yieldcpu;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.Scanner;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.atomic.AtomicBoolean;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        Random random = new Random();
        ArbitraryLowerCaseLetter lowerCaseLetterGenerator = new ArbitraryLowerCaseLetter(random);
        ArbitraryWord wordGenerator = new ArbitraryWord(
                3, 5, random, lowerCaseLetterGenerator);
        ArbitraryInteger batchSizeGenerator = new ArbitraryInteger(100, 200, random);
        ArbitraryInteger breakGenerator = new ArbitraryInteger(50, 1500, random);
        LinkedBlockingQueue<Record> queue = new LinkedBlockingQueue();

        AtomicBoolean stopFlag = new AtomicBoolean(false);
        int eventLimit = 20000;

        Producer producer = new Producer(
                stopFlag, wordGenerator, batchSizeGenerator, breakGenerator, queue);

        StopWatch stopWatch = new StopWatch();

        Scanner scanner = new Scanner(System.in);
        int choice = scanner.nextInt();
        System.out.println("choice="+choice);
        Consumer consumer = null;
        StringBuilder logFileBuilder = new StringBuilder()
                .append("/home/daowen/github/playground/languages/java/yield-cpu/");
        switch (choice) {
            case 1: {
                consumer = new PollingConsumer(eventLimit, queue, stopFlag, stopWatch);
                logFileBuilder.append("polling.txt");
                break;
            }
            case 2: {
                consumer = new TimeOutPollingConsumer(eventLimit, queue, 250, stopFlag, stopWatch);
                logFileBuilder.append("timeout-polling.txt");
                break;
            }
            case 3: {
                consumer = new YieldingConsumer(eventLimit, queue, stopFlag, stopWatch);
                logFileBuilder.append("yielding.txt");
                break;
            }
            case 4: {
                consumer = new SmartPollingConsumer(eventLimit, queue, 250, stopFlag, stopWatch);
                logFileBuilder.append("smart-polling.txt");
                break;
            }
            case 5: {
                consumer = new TimeOutPollingConsumer(eventLimit, queue, 100, stopFlag, stopWatch);
                logFileBuilder.append("timeout-polling-100.txt");
                break;
            }
            case 6: {
                consumer = new SmartPollingConsumer(eventLimit, queue, 100, stopFlag, stopWatch);
                logFileBuilder.append("smart-polling-100.txt");
                break;
            }
            case 7: {
                consumer = new TimeOutPollingConsumer(eventLimit, queue, 500, stopFlag, stopWatch);
                logFileBuilder.append("timeout-polling-500.txt");
                break;
            }
            case 8: {
                consumer = new SmartPollingConsumer(eventLimit, queue, 500, stopFlag, stopWatch);
                logFileBuilder.append("smart-polling-500.txt");
                break;
            }
        };
        if (consumer == null) {
            System.out.println("no choice!");
            return;
        }

        ExecutorService executorService = Executors.newFixedThreadPool(2);

        long startMillis = System.currentTimeMillis();

        executorService.submit(consumer);
        executorService.submit(producer);

        try {
            while (!stopFlag.get()) {
                Thread.sleep(1000);
            }
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        executorService.shutdownNow();

        // System.out.println(consumer.getPerformance());
        long endMillis = System.currentTimeMillis();
        System.out.println("run time (ms) = " + (endMillis - startMillis));

        try {
            String fileName = logFileBuilder.toString();
            System.out.println("writing to " + fileName);
            FileWriter writer = new FileWriter(fileName, true);
            writer.write(consumer.getPerformance().toString() + "\n");
            writer.close();
        } catch (IOException e) {
            System.out.println("encountered error!!");
            System.err.println(e);
        }
    }
}
